// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLj4riOAlDrTg3Zc9aiTLYlEt8AuRxGI4',
    appId: '1:102631890122:web:f45d89e016bd8dd1dee833',
    messagingSenderId: '102631890122',
    projectId: 'e-commerce-app-2c3dc',
    authDomain: 'e-commerce-app-2c3dc.firebaseapp.com',
    storageBucket: 'e-commerce-app-2c3dc.appspot.com',
    measurementId: 'G-ZLK3PX5QFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3f69B7UwJPb8Hmy7ADOym-d94hPysg4',
    appId: '1:102631890122:android:2aeace9974ccef84dee833',
    messagingSenderId: '102631890122',
    projectId: 'e-commerce-app-2c3dc',
    storageBucket: 'e-commerce-app-2c3dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvzEGl7cPBEhtHzrfvirkLpQnvxh1Fr9Y',
    appId: '1:102631890122:ios:be1323352ccba944dee833',
    messagingSenderId: '102631890122',
    projectId: 'e-commerce-app-2c3dc',
    storageBucket: 'e-commerce-app-2c3dc.appspot.com',
    iosBundleId: 'com.example.ecomFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvzEGl7cPBEhtHzrfvirkLpQnvxh1Fr9Y',
    appId: '1:102631890122:ios:158ae8adbf58349bdee833',
    messagingSenderId: '102631890122',
    projectId: 'e-commerce-app-2c3dc',
    storageBucket: 'e-commerce-app-2c3dc.appspot.com',
    iosBundleId: 'com.example.ecomFirebase.RunnerTests',
  );
}
